name: "Protect main branch"

on:
  push:
    branches: [main]

jobs:
  protect:
    runs-on: ubuntu-latest
    steps:
      - name: Set branch protection
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          enforce_admins: true
          required_approving_review_count: 2
          require_code_owner_reviews: true
          dismiss_stale_reviews: true
          required_status_checks: build,test,lint
          strict: true
          require_conversation_resolution: true
          require_signed_commits: true
          require_linear_history: true
          restrict_push_access: true
          allowed_teams: release-managers
